#!/bin/sh
set -e

dir=/usr/src/php

usage() {
    echo "usage: $0 COMMAND"
    echo
    echo "Manage php source tarball lifecycle."
    echo
    echo "Commands:"
    echo "   extract  extract php source tarball into directory $dir if not already done."
    echo "   delete   delete extracted php source located into $dir if not already done."
    echo
}

case "$1" in
    extract)
        apk add --no-cache --virtual .arch-deps p7zip
        mkdir -p "$dir"
        if [ ! -f "$dir/.docker-extracted" ]; then
            echo '- Extracting PHP source into ...' $dir
            7z x -o$dir /usr/src/php.7z && \
            touch "$dir/.docker-extracted" && \
            echo 'PHP source extracted'
        fi
        apk del --purge --no-network .arch-deps
        ;;

    delete)
        rm -rf "$dir"
        ;;

    *)
        usage
        exit 1
        ;;
esac
